# File: .cargo/config.toml

[target.aarch64-linux-android]
ar = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang"

[target.x86_64-linux-android]
linker = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android23-clang"

[env]
# ==== Lokasi NDK ====
ANDROID_NDK = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"
ANDROID_NDK_HOME = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"
ANDROID_NDK_ROOT = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"

# ==== Toolchain CMake ====
CMAKE_TOOLCHAIN_FILE = "/home/arissupriy/Projects/quran-assistant/rust/cmake/android_arm64_toolchain.cmake"
CMAKE_GENERATOR = "Ninja"
CMAKE_MAKE_PROGRAM = "/usr/bin/ninja"

## ==== Target ABI & API Level ====
ANDROID_ABI = "arm64-v8a"
# Prefer numeric API level for some toolchain paths
ANDROID_PLATFORM = "23"
CMAKE_ANDROID_ARCH_ABI = "arm64-v8a"
CMAKE_SYSTEM_NAME = "Android"
CMAKE_SYSTEM_PROCESSOR = "aarch64"
CMAKE_SYSTEM_VERSION = "23"
CMAKE_ANDROID_API = "23"

# (do not override CMAKE_C_COMPILER/CXX; let android.toolchain.cmake set them)

## ==== Make try_compile inherit vars and avoid executable link ====
CMAKE_TRY_COMPILE_PLATFORM_VARIABLES = "ANDROID_ABI;ANDROID_PLATFORM;CMAKE_ANDROID_ARCH_ABI;CMAKE_SYSTEM_NAME;CMAKE_SYSTEM_VERSION"
CMAKE_TRY_COMPILE_TARGET_TYPE = "STATIC_LIBRARY"

## ==== Fix bindgen header include paths for Android target ====
BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android = "--target=aarch64-linux-android23 --sysroot=/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/sysroot -I/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/20/include"
