// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/engine_loader.dart';
import 'api/mushaf.dart';
import 'api/quiz/quiz_fragment_completion.dart';
import 'api/quiz/verse_completion.dart';
import 'api/quran/chapter.dart';
import 'api/quran/metadata.dart';
import 'api/quran/search.dart';
import 'api/quran/similarity.dart';
import 'api/quran/verse.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'data_loader/ayah_texts.dart';
import 'data_loader/chapters.dart';
import 'data_loader/juzs.dart';
import 'data_loader/quiz_models.dart';
import 'data_loader/search_models.dart';
import 'data_loader/valid_matching_ayah.dart';
import 'data_loader/verse_by_chapter.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, Uint8List> dco_decode_Map_String_list_prim_u_8_strict_None(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AyahText dco_decode_ayah_text(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Chapter dco_decode_box_autoadd_chapter(dynamic raw);

  @protected
  Juz dco_decode_box_autoadd_juz(dynamic raw);

  @protected
  QuizFilter dco_decode_box_autoadd_quiz_filter(dynamic raw);

  @protected
  QuizGenerationError dco_decode_box_autoadd_quiz_generation_error(dynamic raw);

  @protected
  QuizQuestion dco_decode_box_autoadd_quiz_question(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Verse dco_decode_box_autoadd_verse(dynamic raw);

  @protected
  Word dco_decode_box_autoadd_word(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GlyphPosition dco_decode_glyph_position(dynamic raw);

  @protected
  Juz dco_decode_juz(dynamic raw);

  @protected
  JuzWithPage dco_decode_juz_with_page(dynamic raw);

  @protected
  List<AyahText> dco_decode_list_ayah_text(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<GlyphPosition> dco_decode_list_glyph_position(dynamic raw);

  @protected
  List<Juz> dco_decode_list_juz(dynamic raw);

  @protected
  List<JuzWithPage> dco_decode_list_juz_with_page(dynamic raw);

  @protected
  List<Uint32List> dco_decode_list_list_prim_u_32_strict(dynamic raw);

  @protected
  List<MatchedAyah> dco_decode_list_matched_ayah(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QuizOption> dco_decode_list_quiz_option(dynamic raw);

  @protected
  List<QuizQuestion> dco_decode_list_quiz_question(dynamic raw);

  @protected
  List<(String, Uint8List)> dco_decode_list_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<Translation> dco_decode_list_translation(dynamic raw);

  @protected
  List<Word> dco_decode_list_word(dynamic raw);

  @protected
  List<WordResult> dco_decode_list_word_result(dynamic raw);

  @protected
  MatchedAyah dco_decode_matched_ayah(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Chapter? dco_decode_opt_box_autoadd_chapter(dynamic raw);

  @protected
  Juz? dco_decode_opt_box_autoadd_juz(dynamic raw);

  @protected
  QuizGenerationError? dco_decode_opt_box_autoadd_quiz_generation_error(
    dynamic raw,
  );

  @protected
  QuizQuestion? dco_decode_opt_box_autoadd_quiz_question(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Verse? dco_decode_opt_box_autoadd_verse(dynamic raw);

  @protected
  Word? dco_decode_opt_box_autoadd_word(dynamic raw);

  @protected
  List<GlyphPosition>? dco_decode_opt_list_glyph_position(dynamic raw);

  @protected
  Uint32List? dco_decode_opt_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  QuizFilter dco_decode_quiz_filter(dynamic raw);

  @protected
  QuizGenerationError dco_decode_quiz_generation_error(dynamic raw);

  @protected
  QuizGenerationResult dco_decode_quiz_generation_result(dynamic raw);

  @protected
  QuizOption dco_decode_quiz_option(dynamic raw);

  @protected
  QuizQuestion dco_decode_quiz_question(dynamic raw);

  @protected
  QuizQuestions dco_decode_quiz_questions(dynamic raw);

  @protected
  QuizScope dco_decode_quiz_scope(dynamic raw);

  @protected
  (String, Uint8List) dco_decode_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  TranslatedName dco_decode_translated_name(dynamic raw);

  @protected
  Translation dco_decode_translation(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Verse dco_decode_verse(dynamic raw);

  @protected
  Word dco_decode_word(dynamic raw);

  @protected
  WordResult dco_decode_word_result(dynamic raw);

  @protected
  WordTranslation dco_decode_word_translation(dynamic raw);

  @protected
  WordTransliteration dco_decode_word_transliteration(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Uint8List> sse_decode_Map_String_list_prim_u_8_strict_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AyahText sse_decode_ayah_text(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_box_autoadd_chapter(SseDeserializer deserializer);

  @protected
  Juz sse_decode_box_autoadd_juz(SseDeserializer deserializer);

  @protected
  QuizFilter sse_decode_box_autoadd_quiz_filter(SseDeserializer deserializer);

  @protected
  QuizGenerationError sse_decode_box_autoadd_quiz_generation_error(
    SseDeserializer deserializer,
  );

  @protected
  QuizQuestion sse_decode_box_autoadd_quiz_question(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Verse sse_decode_box_autoadd_verse(SseDeserializer deserializer);

  @protected
  Word sse_decode_box_autoadd_word(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GlyphPosition sse_decode_glyph_position(SseDeserializer deserializer);

  @protected
  Juz sse_decode_juz(SseDeserializer deserializer);

  @protected
  JuzWithPage sse_decode_juz_with_page(SseDeserializer deserializer);

  @protected
  List<AyahText> sse_decode_list_ayah_text(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<GlyphPosition> sse_decode_list_glyph_position(
    SseDeserializer deserializer,
  );

  @protected
  List<Juz> sse_decode_list_juz(SseDeserializer deserializer);

  @protected
  List<JuzWithPage> sse_decode_list_juz_with_page(SseDeserializer deserializer);

  @protected
  List<Uint32List> sse_decode_list_list_prim_u_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MatchedAyah> sse_decode_list_matched_ayah(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QuizOption> sse_decode_list_quiz_option(SseDeserializer deserializer);

  @protected
  List<QuizQuestion> sse_decode_list_quiz_question(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Uint8List)> sse_decode_list_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<Translation> sse_decode_list_translation(SseDeserializer deserializer);

  @protected
  List<Word> sse_decode_list_word(SseDeserializer deserializer);

  @protected
  List<WordResult> sse_decode_list_word_result(SseDeserializer deserializer);

  @protected
  MatchedAyah sse_decode_matched_ayah(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Chapter? sse_decode_opt_box_autoadd_chapter(SseDeserializer deserializer);

  @protected
  Juz? sse_decode_opt_box_autoadd_juz(SseDeserializer deserializer);

  @protected
  QuizGenerationError? sse_decode_opt_box_autoadd_quiz_generation_error(
    SseDeserializer deserializer,
  );

  @protected
  QuizQuestion? sse_decode_opt_box_autoadd_quiz_question(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Verse? sse_decode_opt_box_autoadd_verse(SseDeserializer deserializer);

  @protected
  Word? sse_decode_opt_box_autoadd_word(SseDeserializer deserializer);

  @protected
  List<GlyphPosition>? sse_decode_opt_list_glyph_position(
    SseDeserializer deserializer,
  );

  @protected
  Uint32List? sse_decode_opt_list_prim_u_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  QuizFilter sse_decode_quiz_filter(SseDeserializer deserializer);

  @protected
  QuizGenerationError sse_decode_quiz_generation_error(
    SseDeserializer deserializer,
  );

  @protected
  QuizGenerationResult sse_decode_quiz_generation_result(
    SseDeserializer deserializer,
  );

  @protected
  QuizOption sse_decode_quiz_option(SseDeserializer deserializer);

  @protected
  QuizQuestion sse_decode_quiz_question(SseDeserializer deserializer);

  @protected
  QuizQuestions sse_decode_quiz_questions(SseDeserializer deserializer);

  @protected
  QuizScope sse_decode_quiz_scope(SseDeserializer deserializer);

  @protected
  (String, Uint8List) sse_decode_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  TranslatedName sse_decode_translated_name(SseDeserializer deserializer);

  @protected
  Translation sse_decode_translation(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  Verse sse_decode_verse(SseDeserializer deserializer);

  @protected
  Word sse_decode_word(SseDeserializer deserializer);

  @protected
  WordResult sse_decode_word_result(SseDeserializer deserializer);

  @protected
  WordTranslation sse_decode_word_translation(SseDeserializer deserializer);

  @protected
  WordTransliteration sse_decode_word_transliteration(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_prim_u_8_strict_None(
    Map<String, Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ayah_text(AyahText self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_juz(Juz self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_quiz_filter(
    QuizFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quiz_generation_error(
    QuizGenerationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quiz_question(
    QuizQuestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_verse(Verse self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_word(Word self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_glyph_position(GlyphPosition self, SseSerializer serializer);

  @protected
  void sse_encode_juz(Juz self, SseSerializer serializer);

  @protected
  void sse_encode_juz_with_page(JuzWithPage self, SseSerializer serializer);

  @protected
  void sse_encode_list_ayah_text(List<AyahText> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_glyph_position(
    List<GlyphPosition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_juz(List<Juz> self, SseSerializer serializer);

  @protected
  void sse_encode_list_juz_with_page(
    List<JuzWithPage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_32_strict(
    List<Uint32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_matched_ayah(
    List<MatchedAyah> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_quiz_option(
    List<QuizOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_quiz_question(
    List<QuizQuestion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_prim_u_8_strict(
    List<(String, Uint8List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_translation(
    List<Translation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_word(List<Word> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_result(
    List<WordResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matched_ayah(MatchedAyah self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chapter(
    Chapter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_juz(Juz? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_quiz_generation_error(
    QuizGenerationError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_quiz_question(
    QuizQuestion? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_verse(Verse? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_word(Word? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_glyph_position(
    List<GlyphPosition>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_32_strict(
    Uint32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quiz_filter(QuizFilter self, SseSerializer serializer);

  @protected
  void sse_encode_quiz_generation_error(
    QuizGenerationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quiz_generation_result(
    QuizGenerationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quiz_option(QuizOption self, SseSerializer serializer);

  @protected
  void sse_encode_quiz_question(QuizQuestion self, SseSerializer serializer);

  @protected
  void sse_encode_quiz_questions(QuizQuestions self, SseSerializer serializer);

  @protected
  void sse_encode_quiz_scope(QuizScope self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_prim_u_8_strict(
    (String, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_translated_name(
    TranslatedName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_translation(Translation self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verse(Verse self, SseSerializer serializer);

  @protected
  void sse_encode_word(Word self, SseSerializer serializer);

  @protected
  void sse_encode_word_result(WordResult self, SseSerializer serializer);

  @protected
  void sse_encode_word_translation(
    WordTranslation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_word_transliteration(
    WordTransliteration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
