// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Non-Android stub: recorder is only supported on Android. Provide safe stubs
// so analyzer doesn't error on missing generated symbols.
Future<void> start({required int sampleRate}) async {
  throw UnsupportedError('Recorder is only supported on Android');
}

Future<void> stop() async {
  throw UnsupportedError('Recorder is only supported on Android');
}
