[target.aarch64-linux-android]
linker = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang"

[target.x86_64-linux-android]
linker = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android23-clang"

[env]
ANDROID_NDK = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"
ANDROID_NDK_HOME = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"
ANDROID_NDK_ROOT = "/home/arissupriy/Android/Sdk/ndk/29.0.13599879"
CMAKE_MAKE_PROGRAM = "/usr/bin/ninja"
CMAKE_TOOLCHAIN_FILE = "/home/arissupriy/Projects/quran-assistant/rust/cmake/android_arm64_toolchain.cmake"
CMAKE_GENERATOR = "Ninja"

## Ensure correct Android arch/platform during CMake configure
# Use both CMAKE_* and ANDROID_* knobs to satisfy various build scripts
ANDROID_ABI = "arm64-v8a"
# Some toolchains expect numeric API level, not android-XX
ANDROID_PLATFORM = "23"
CMAKE_ANDROID_ARCH_ABI = "arm64-v8a"
CMAKE_SYSTEM_NAME = "Android"
CMAKE_SYSTEM_PROCESSOR = "aarch64"
# Also set the API level via CMake variables
CMAKE_SYSTEM_VERSION = "23"
CMAKE_ANDROID_API = "23"

# Make sure try_compile inherits these platform variables
CMAKE_TRY_COMPILE_PLATFORM_VARIABLES = "ANDROID_ABI;ANDROID_PLATFORM;CMAKE_ANDROID_ARCH_ABI;CMAKE_SYSTEM_NAME;CMAKE_SYSTEM_VERSION"
# Avoid linking executables during try_compile which can pick wrong defaults
CMAKE_TRY_COMPILE_TARGET_TYPE = "STATIC_LIBRARY"

# Per-target overrides (some build scripts read these)
CMAKE_GENERATOR_aarch64-linux-android = "Ninja"
CMAKE_TOOLCHAIN_FILE_aarch64-linux-android = "/home/arissupriy/Projects/quran-assistant/rust/cmake/android_arm64_toolchain.cmake"
