// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/ayah_texts.dart';
import '../../data_loader/chapters.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mengembalikan daftar lengkap semua bab (surah) Al-Quran.
Future<List<Chapter>> getAllChapters() =>
    RustLib.instance.api.crateApiQuranChapterGetAllChapters();

/// Mengembalikan nama sederhana (simple name) dari bab berdasarkan ID bab.
Future<String> getChapterNameSimple({required int chapterId}) => RustLib
    .instance
    .api
    .crateApiQuranChapterGetChapterNameSimple(chapterId: chapterId);

/// Mengembalikan detail lengkap bab berdasarkan ID bab.
Future<Chapter?> getChapterDetails({required int chapterId}) => RustLib
    .instance
    .api
    .crateApiQuranChapterGetChapterDetails(chapterId: chapterId);

/// Mengembalikan semua ayat dalam surah (bab) tertentu berdasarkan ID bab.
Future<List<AyahText>> getAyahsBySurah({required int chapterId}) => RustLib
    .instance
    .api
    .crateApiQuranChapterGetAyahsBySurah(chapterId: chapterId);
