// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/chapters.dart';
import '../../data_loader/juzs.dart';
import '../../data_loader/mushaf_page_info.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mengembalikan informasi lengkap tentang Juz berdasarkan nomornya.
/// Jika tidak ditemukan, akan mengembalikan `None` di sisi Dart.
Future<Juz?> getJuzDetails({required int juzNumber}) => RustLib.instance.api
    .crateApiQuranMetadataGetJuzDetails(juzNumber: juzNumber);

/// Mengembalikan seluruh daftar Juz.
Future<List<Juz>> getAllJuzs() =>
    RustLib.instance.api.crateApiQuranMetadataGetAllJuzs();

Future<int> getPageFromVerseId({required int verseId}) => RustLib.instance.api
    .crateApiQuranMetadataGetPageFromVerseId(verseId: verseId);

Future<List<JuzWithPage>> getAllJuzsWithPage() =>
    RustLib.instance.api.crateApiQuranMetadataGetAllJuzsWithPage();

/// Mengambil semua informasi kontekstual (nama surah, juz, kata awal halaman berikutnya) untuk halaman Mushaf tertentu.
Future<MushafPageInfo> getMushafPageContextInfo({required int pageNumber}) =>
    RustLib.instance.api.crateApiQuranMetadataGetMushafPageContextInfo(
      pageNumber: pageNumber,
    );

Future<Chapter?> getChapterByPageNumber({required int pageNumber}) => RustLib
    .instance
    .api
    .crateApiQuranMetadataGetChapterByPageNumber(pageNumber: pageNumber);
