// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/valid_matching_ayah.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<MatchedAyah>> getSimilarAyahs({required String verseKey}) => RustLib
    .instance
    .api
    .crateApiQuranSimilarityGetSimilarAyahs(verseKey: verseKey);

Future<List<MatchedAyah>> getSimilarAyahsInverted({required String verseKey}) =>
    RustLib.instance.api.crateApiQuranSimilarityGetSimilarAyahsInverted(
      verseKey: verseKey,
    );
