// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/ayah_texts.dart';
import '../../data_loader/verse_by_chapter.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mengembalikan teks ayat Uthmani (lengkap dengan harakat) berdasarkan kunci ayat (contoh: "1:1").
Future<String?> getVerseTextUthmani({required String verseKey}) => RustLib
    .instance
    .api
    .crateApiQuranVerseGetVerseTextUthmani(verseKey: verseKey);

Future<AyahText> getVerseTexts({required String verseKey}) =>
    RustLib.instance.api.crateApiQuranVerseGetVerseTexts(verseKey: verseKey);

/// Mengembalikan nomor juz untuk sebuah ayat berdasarkan kunci ayat.
Future<int?> getJuzNumberForVerse({required String verseKey}) => RustLib
    .instance
    .api
    .crateApiQuranVerseGetJuzNumberForVerse(verseKey: verseKey);

/// Mengembalikan data lengkap ayat (termasuk kata-kata dan terjemahan) berdasarkan nomor bab dan nomor ayat.
Future<Verse?> getVerseByChapterAndVerseNumber({
  required int chapterNumber,
  required int verseNumber,
}) => RustLib.instance.api.crateApiQuranVerseGetVerseByChapterAndVerseNumber(
  chapterNumber: chapterNumber,
  verseNumber: verseNumber,
);

/// Mengembalikan teks terjemahan untuk ayat tertentu berdasarkan kunci ayat dan ID sumber terjemahan.
Future<String?> getTranslationText({required String verseKey}) => RustLib
    .instance
    .api
    .crateApiQuranVerseGetTranslationText(verseKey: verseKey);

/// Mengembalikan detail objek Word (kata) berdasarkan `word_key`, misalnya "2:1:3"
Future<Translation?> getWordDetails({required String verseKey}) =>
    RustLib.instance.api.crateApiQuranVerseGetWordDetails(verseKey: verseKey);

Future<VerseDetailWithWords?> getVerseDetails({required String verseKey}) =>
    RustLib.instance.api.crateApiQuranVerseGetVerseDetails(verseKey: verseKey);
