// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Fungsi ini dipanggil dari Flutter untuk memuat seluruh EngineData dari assets.
/// Wajib dipanggil sebelum menggunakan fitur seperti pencarian, tafsir, dll.
/// Bisa memuat pertama kali atau override jika sudah ada.
Future<void> loadEngineDataFromFlutterAssets({
  required Map<String, Uint8List> map,
}) => RustLib.instance.api.crateApiEngineLoaderLoadEngineDataFromFlutterAssets(
  map: map,
);

/// Hanya reset EngineData jika sudah pernah di-load sebelumnya.
/// Akan gagal jika belum pernah dipanggil.
Future<void> resetEngineFromFlutter({required Map<String, Uint8List> map}) =>
    RustLib.instance.api.crateApiEngineLoaderResetEngineFromFlutter(map: map);
