// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MushafBundle`

Future<bool> openMushafPack({required String path}) =>
    RustLib.instance.api.crateApiMushafOpenMushafPack(path: path);

Future<Uint8List?> getPageImage({required int page}) =>
    RustLib.instance.api.crateApiMushafGetPageImage(page: page);

Future<List<GlyphPosition>?> getPageMetadata({required int page}) =>
    RustLib.instance.api.crateApiMushafGetPageMetadata(page: page);
