// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `push`, `take`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<void> recorderInit() =>
    RustLib.instance.api.crateApiRecorderRecorderInit();

Future<Int16List> recorderTakeSamples() =>
    RustLib.instance.api.crateApiRecorderRecorderTakeSamples();

Future<void> recorderStart({required int sampleRate}) =>
    RustLib.instance.api.crateApiRecorderRecorderStart(sampleRate: sampleRate);

Future<void> recorderStop() =>
    RustLib.instance.api.crateApiRecorderRecorderStop();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SharedBuffer>>
abstract class SharedBuffer implements RustOpaqueInterface {
  static Future<SharedBuffer> default_() =>
      RustLib.instance.api.crateApiRecorderSharedBufferDefault();
}
