// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/quiz_models.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_single_verse_order_quiz`, `parse_key`

Future<QuizQuestions> generateBatchVerseOrderQuizzes({
  required QuizFilter filter,
}) => RustLib.instance.api.crateApiQuizVerseOrderGenerateBatchVerseOrderQuizzes(
  filter: filter,
);
