// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../data_loader/quiz_models.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Membuat batch kuis tebak ayat sebelumnya.
Future<QuizQuestions> generateBatchVersePreviousQuizzes({
  required QuizFilter filter,
}) => RustLib.instance.api
    .crateApiQuizVersePreviousGenerateBatchVersePreviousQuizzes(filter: filter);

/// Membuat kuis "Tebak Ayat Sebelumnya"
Future<QuizGenerationResult> generatePreviousVerseQuiz({
  required QuizFilter filter,
}) => RustLib.instance.api.crateApiQuizVersePreviousGeneratePreviousVerseQuiz(
  filter: filter,
);
