// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AyahText {
  final String verseKey;
  final String textUthmaniSimple;
  final String textUthmani;
  final String textQpcHafs;

  const AyahText({
    required this.verseKey,
    required this.textUthmaniSimple,
    required this.textUthmani,
    required this.textQpcHafs,
  });

  @override
  int get hashCode =>
      verseKey.hashCode ^
      textUthmaniSimple.hashCode ^
      textUthmani.hashCode ^
      textQpcHafs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AyahText &&
          runtimeType == other.runtimeType &&
          verseKey == other.verseKey &&
          textUthmaniSimple == other.textUthmaniSimple &&
          textUthmani == other.textUthmani &&
          textQpcHafs == other.textQpcHafs;
}
