// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Juz {
  final int id;
  final int juzNumber;
  final Map<String, String> verseMapping;
  final int firstVerseId;
  final int lastVerseId;
  final int versesCount;

  const Juz({
    required this.id,
    required this.juzNumber,
    required this.verseMapping,
    required this.firstVerseId,
    required this.lastVerseId,
    required this.versesCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      juzNumber.hashCode ^
      verseMapping.hashCode ^
      firstVerseId.hashCode ^
      lastVerseId.hashCode ^
      versesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Juz &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          juzNumber == other.juzNumber &&
          verseMapping == other.verseMapping &&
          firstVerseId == other.firstVerseId &&
          lastVerseId == other.lastVerseId &&
          versesCount == other.versesCount;
}

class JuzWithPage {
  final Juz juz;
  final int pageNumber;

  const JuzWithPage({required this.juz, required this.pageNumber});

  @override
  int get hashCode => juz.hashCode ^ pageNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JuzWithPage &&
          runtimeType == other.runtimeType &&
          juz == other.juz &&
          pageNumber == other.pageNumber;
}
