// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MushafPageInfo {
  final String surahNameArabic;
  final int juzNumber;
  final int pageNumber;
  final String nextPageRouteText;

  const MushafPageInfo({
    required this.surahNameArabic,
    required this.juzNumber,
    required this.pageNumber,
    required this.nextPageRouteText,
  });

  @override
  int get hashCode =>
      surahNameArabic.hashCode ^
      juzNumber.hashCode ^
      pageNumber.hashCode ^
      nextPageRouteText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MushafPageInfo &&
          runtimeType == other.runtimeType &&
          surahNameArabic == other.surahNameArabic &&
          juzNumber == other.juzNumber &&
          pageNumber == other.pageNumber &&
          nextPageRouteText == other.nextPageRouteText;
}
