// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GlyphPosition {
  final int glyphId;
  final int pageNumber;
  final int lineNumber;
  final int sura;
  final int ayah;
  final int wordPosition;
  final int minX;
  final int maxX;
  final int minY;
  final int maxY;

  const GlyphPosition({
    required this.glyphId,
    required this.pageNumber,
    required this.lineNumber,
    required this.sura,
    required this.ayah,
    required this.wordPosition,
    required this.minX,
    required this.maxX,
    required this.minY,
    required this.maxY,
  });

  @override
  int get hashCode =>
      glyphId.hashCode ^
      pageNumber.hashCode ^
      lineNumber.hashCode ^
      sura.hashCode ^
      ayah.hashCode ^
      wordPosition.hashCode ^
      minX.hashCode ^
      maxX.hashCode ^
      minY.hashCode ^
      maxY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlyphPosition &&
          runtimeType == other.runtimeType &&
          glyphId == other.glyphId &&
          pageNumber == other.pageNumber &&
          lineNumber == other.lineNumber &&
          sura == other.sura &&
          ayah == other.ayah &&
          wordPosition == other.wordPosition &&
          minX == other.minX &&
          maxX == other.maxX &&
          minY == other.minY &&
          maxY == other.maxY;
}
