// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Struktur untuk menyimpan hasil pencarian yang akan dikembalikan ke Dart.
class SearchResult {
  final String verseKey;
  final double score;
  final List<WordResult> words;

  const SearchResult({
    required this.verseKey,
    required this.score,
    required this.words,
  });

  @override
  int get hashCode => verseKey.hashCode ^ score.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          verseKey == other.verseKey &&
          score == other.score &&
          words == other.words;
}

/// Struktur untuk merepresentasikan detail kata dalam hasil pencarian.
/// Ini adalah versi Word dari data asli, ditambah dengan field untuk highlight.
class WordResult {
  final int id;
  final int position;
  final String textUthmani;
  final String translationText;
  final bool highlighted;

  const WordResult({
    required this.id,
    required this.position,
    required this.textUthmani,
    required this.translationText,
    required this.highlighted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      textUthmani.hashCode ^
      translationText.hashCode ^
      highlighted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          textUthmani == other.textUthmani &&
          translationText == other.translationText &&
          highlighted == other.highlighted;
}
