// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MatchedAyah {
  final String matchedAyahKey;
  final int matchedWordsCount;
  final int coverage;
  final int score;
  final List<Uint32List> matchWords;

  const MatchedAyah({
    required this.matchedAyahKey,
    required this.matchedWordsCount,
    required this.coverage,
    required this.score,
    required this.matchWords,
  });

  @override
  int get hashCode =>
      matchedAyahKey.hashCode ^
      matchedWordsCount.hashCode ^
      coverage.hashCode ^
      score.hashCode ^
      matchWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchedAyah &&
          runtimeType == other.runtimeType &&
          matchedAyahKey == other.matchedAyahKey &&
          matchedWordsCount == other.matchedWordsCount &&
          coverage == other.coverage &&
          score == other.score &&
          matchWords == other.matchWords;
}
