// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Translation {
  final String text;
  final Map<String, String> footnotes;

  const Translation({required this.text, required this.footnotes});

  @override
  int get hashCode => text.hashCode ^ footnotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Translation &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          footnotes == other.footnotes;
}

class Verse {
  final int id;
  final int verseNumber;
  final String verseKey;
  final int hizbNumber;
  final int rubElHizbNumber;
  final int rukuNumber;
  final int manzilNumber;
  final int? sajdahNumber;
  final int pageNumber;
  final int juzNumber;
  final List<String> wordIds;
  final List<Translation> translations;

  const Verse({
    required this.id,
    required this.verseNumber,
    required this.verseKey,
    required this.hizbNumber,
    required this.rubElHizbNumber,
    required this.rukuNumber,
    required this.manzilNumber,
    this.sajdahNumber,
    required this.pageNumber,
    required this.juzNumber,
    required this.wordIds,
    required this.translations,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      verseNumber.hashCode ^
      verseKey.hashCode ^
      hizbNumber.hashCode ^
      rubElHizbNumber.hashCode ^
      rukuNumber.hashCode ^
      manzilNumber.hashCode ^
      sajdahNumber.hashCode ^
      pageNumber.hashCode ^
      juzNumber.hashCode ^
      wordIds.hashCode ^
      translations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Verse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          verseNumber == other.verseNumber &&
          verseKey == other.verseKey &&
          hizbNumber == other.hizbNumber &&
          rubElHizbNumber == other.rubElHizbNumber &&
          rukuNumber == other.rukuNumber &&
          manzilNumber == other.manzilNumber &&
          sajdahNumber == other.sajdahNumber &&
          pageNumber == other.pageNumber &&
          juzNumber == other.juzNumber &&
          wordIds == other.wordIds &&
          translations == other.translations;
}
